// Generated by CoffeeScript 1.4.0
(function() {

  window.Split = {
    test: function(name, groups, callback) {
      var group;
      if (groups == null) {
        groups = null;
      }
      if (callback == null) {
        callback = null;
      }
      if ($.cookie(name) || !(groups != null)) {
        group = $.cookie(name);
      } else {
        group = this.selectRandom(groups);
        $.cookie(name, group);
      }
      if (callback != null) {
        return callback(group);
      } else {
        return group;
      }
    },
    clear: function(name) {
      return $.removeCookie(name);
    },
    selectRandom: function(groups) {
      return groups[Math.floor(Math.random() * groups.length)];
    }
  };

}).call(this);
